# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190116_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='mp3', max_length=10),
        ),
    ]
